// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/portfolio-redesign/SlateGold.tsx": () => import("../components/mockups/portfolio-redesign/SlateGold.tsx"),
  "./components/mockups/portfolio-redesign/WarmClean.tsx": () => import("../components/mockups/portfolio-redesign/WarmClean.tsx")
};
